// Generated by https://quicktype.io

export interface loginProps {
  id: number;
  name: string;
  lastname: string;
  email: string;
  password: Password;
  phone: string;
  phone2: null;
  deleted_at: null;
  created_at: string;
  updated_at: string;
}

export enum Password {
  Secret = 'secret',
}
